pipeline {
  agent {
    docker {image 'python:3.11-slim'}
  }
  stages {
    stage ("Python version check") {
      steps {
        sh 'python3 --version'
      }
    }
    stage("Running python program") {
      steps {
        sh 'python3 "second pipeline/simple.py"'
      }
    }
  }
}